name: Tests
on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker-compose build meldingen-core

      - name: Test
        run: docker-compose run --rm meldingen-core pytest --cov --cov-fail-under=100 -v
